# Generated by Django 4.2.3 on 2023-07-29 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('detail', models.TextField()),
                ('price', models.FloatField(default=0.0)),
                ('image', models.ImageField(default='product.jpg', upload_to='images/')),
            ],
        ),
    ]
